In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
train.tail()

portfolio_id desk_id    office_id pf_category  start_date         sold  \
9361   PF00014131     NaN  OFF00001002           C    20160624   17864000.0   
9362   PF00014132     NaN  OFF00001002           C    20160624   82500000.0   
9363   PF00014145     NaN  OFF00001002           C    20160628  110000000.0   
9364   PF00014146     NaN  OFF00001002           C    20160628   33000000.0   
9365   PF00014148     NaN  OFF00001002           C    20160628   89562000.0   

     country_code  euribor_rate currency  libor_rate        bought  \
9361            M      -0.00349      CHF   -0.556873  1.786333e+07   
9362            M      -0.00349      CHF   -0.556873  8.249198e+07   
9363            M      -0.00349      CHF   -0.556873  1.099893e+08   
9364            M      -0.00349      CHF   -0.556873  3.299679e+07   
9365            M      -0.00349      CHF   -0.556873  8.955329e+07   

      creation_date indicator_code  sell_date type hedge_value status  return  
9361       20160624           True   20160627    E       False   True  0.0054  
9362       20160624           True   20160701    E       False   True  0.0060  
9363       20160628           True   20160705    E       False   True  0.0060  
9364       20160628           True   20160705    E       False   True  0.0060  
9365       20160628           True   20160705    E       False   True  0.0060

In [4]:
test.tail()

portfolio_id desk_id    office_id pf_category  start_date         sold  \
4796   PF00014118     NaN  OFF00001002           C    20160621   55000000.0   
4797   PF00014120     NaN  OFF00001002           C    20160621  138809000.0   
4798   PF00014123     NaN  OFF00001002           B    20160622   28732000.0   
4799   PF00014127     NaN  OFF00001002           C    20160623   34419000.0   
4800   PF00014147     NaN  OFF00001002           C    20160628   53713000.0   

     country_code  euribor_rate currency  libor_rate        bought  \
4796            M      -0.00349      CHF   -0.556873  5.499519e+07   
4797            M      -0.00349      CHF   -0.556873  1.387969e+08   
4798            N      -0.00349      GBP    0.960652  2.872930e+07   
4799            M      -0.00349      CHF   -0.556873  3.441599e+07   
4800            M      -0.00349      CHF   -0.556873  5.370778e+07   

      creation_date indicator_code  sell_date type hedge_value status  
4796       20160621           True   20160628    E       False   True  
4797       20160621           True   20160628    E       False   True  
4798       20160622           True   20160629    C       False   True  
4799       20160623           True   20160630    E       False   True  
4800       20160628           True   20160705    E       False   True

In [5]:
# check missing values per column
train.isnull().sum(axis=0)/train.shape[0]

portfolio_id      0.000000
desk_id           0.391309
office_id         0.000000
pf_category       0.000000
start_date        0.000000
sold              0.000214
country_code      0.000000
euribor_rate      0.000000
currency          0.000000
libor_rate        0.050609
bought            0.000214
creation_date     0.000000
indicator_code    0.608477
sell_date         0.000000
type              0.000000
hedge_value       0.608691
status            0.329276
return            0.000000
dtype: float64

In [6]:
train['libor_rate'].fillna(-999, inplace=True)
test['libor_rate'].fillna(-999, inplace=True)

train['indicator_code'].fillna(0, inplace=True)
test['indicator_code'].fillna(0, inplace=True)

train['hedge_value'].fillna(0, inplace=True)
test['hedge_value'].fillna(0, inplace=True)

In [7]:
train['desk_id'].fillna(method='ffill',inplace=True)
test['desk_id'].fillna(method='ffill',inplace=True)

train['sold'].fillna(0,inplace=True)
test['sold'].fillna(0, inplace=True)

train['bought'].fillna(0, inplace=True)
test['bought'].fillna(0, inplace=True)

train['status'].fillna(0, inplace=True)
test['status'].fillna(0, inplace=True)

In [8]:
train["pf_category"].unique()

array(['B', 'A', 'C', 'D', 'E'], dtype=object)

In [9]:
#encode as integer
mapping = {'A':0, 'B':1, 'C':2, 'D':3, 'E':4}
train = train.replace({'pf_category':mapping})
test = test.replace({'pf_category':mapping})

In [10]:
train["country_code"].unique()

array(['T', 'N', 'M', 'Z', 'U'], dtype=object)

In [11]:
#encode as integer
mapping = {'T':0, 'N':1, 'M':2, 'Z':3, 'U':4}
train = train.replace({'country_code':mapping})
test = test.replace({'country_code':mapping})

In [12]:
train["currency"].unique()

array(['USD', 'GBP', 'CHF', 'EUR', 'JPY'], dtype=object)

In [13]:
#encode as integer
mapping = {'USD':0, 'GBP':1, 'CHF':2, 'EUR':3, 'JPY':4}
train = train.replace({'currency':mapping})
test = test.replace({'currency':mapping})

In [14]:
train["indicator_code"].unique()

array([0, True], dtype=object)

In [15]:
#encode as integer
mapping = {'True':0, '0':1}
train = train.replace({'indicator_code':mapping})
test = test.replace({'indicator_code':mapping})

In [16]:
train["type"].unique()

array(['B', 'C', 'A', 'D', 'E', 'F', 'G', 'H'], dtype=object)

In [17]:
#encode as integer
mapping = {'A':0, 'B':1, 'C':2, 'D':3, 'E':4, 'F':5, 'G':6, 'H':7}
train = train.replace({'type':mapping})
test = test.replace({'type':mapping})

In [18]:
train["hedge_value"].unique()

array([0, True], dtype=object)

In [19]:
#encode as integer
mapping = {'True':0, '0':1}
train = train.replace({'hedge_value':mapping})
test = test.replace({'hedge_value':mapping})

In [20]:
train["status"].unique()

array([0, True], dtype=object)

In [21]:
#encode as integer
mapping = {'True':0, '0':1}
train = train.replace({'status':mapping})
test = test.replace({'status':mapping})

In [22]:
train['desk_id']=train['desk_id'].str[3:]
test['desk_id']=test['desk_id'].str[3:]

In [23]:
train['office_id']=train['office_id'].str[3:]
test['office_id']=test['office_id'].str[3:]

In [24]:
y_train = train['return']
test_id = test['portfolio_id']

In [25]:
train.drop(['return','portfolio_id'], inplace=True, axis=1)
test.drop(['portfolio_id'],inplace=True,axis=1)

In [26]:
from tpot import TPOTRegressor

In [33]:
pipeline_optimizer = TPOTRegressor(generations=5, population_size=100,
                         offspring_size=None, mutation_rate=0.9,
                         crossover_rate=0.1,
                         scoring='neg_mean_squared_error', cv=5,
                         subsample=1.0, n_jobs=1,
                         max_time_mins=None, max_eval_time_mins=5,
                         random_state=None, config_dict=None,
                         warm_start=False,
                         periodic_checkpoint_folder=None,
                         verbosity=2,
                         disable_update_check=False)

Version 0.9.0 of tpot is outdated. Version 0.9.1 was released Friday November 10, 2017.


In [34]:
pipeline_optimizer.fit(train.tail(10000), y_train.tail(10000))

Generation 1 - Current best internal CV score: 0.00020736690056159923


Generation 2 - Current best internal CV score: 0.00018367567112010099


Generation 3 - Current best internal CV score: 0.00012764815487413273


Generation 4 - Current best internal CV score: 0.00012764815487413273


Generation 5 - Current best internal CV score: 0.0001222450583287392



Best pipeline: LassoLarsCV(PolynomialFeatures(StandardScaler(input_matrix), degree=2, include_bias=False, interaction_only=False), normalize=False)


TPOTRegressor(config_dict={'sklearn.preprocessing.Binarizer': {'threshold': array([ 0.  ,  0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,
        0.45,  0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,
        0.9 ,  0.95,  1.  ])}, 'sklearn.kernel_approximation.RBFSampler': {'gamma': array([ 0.  , ...        0.45,  0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,
        0.9 ,  0.95,  1.  ])}},
       crossover_rate=0.1, cv=5, disable_update_check=False,
       early_stop=None, generations=5, max_eval_time_mins=5,
       max_time_mins=None, mutation_rate=0.9, n_jobs=1, offspring_size=100,
       periodic_checkpoint_folder=None, population_size=100,
       random_state=None, scoring=None, subsample=1.0, verbosity=2,
       warm_start=False)

In [35]:
pred=pipeline_optimizer.predict(test)

In [36]:
columns = ['return']
sub = pd.DataFrame(data=pred, columns=columns)
sub['portfolio_id'] = test_id
sub = sub[['portfolio_id','return']]
sub.to_csv("return.csv", index=False)